name: Check for stale issues and PRs

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1 # See: https://github.com/actions/stale
